# -*- coding: utf-8 -*-
"""stack1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3PQNcE7JAwC9o09n4CDSApz_DBSiVjQ
"""

class stack:
  def __init__(self):
    self.mylist=[]

  def is_empty(self):
    return len(self.mylist)==0
  def push(self,data):
    self.mylist.append(data)

  def pop(self):
    if not self.is_empty():
      return self.mylist.pop()

    else:
      raise IndexError("No value available to dlt")
  def peek(self):
    return self.mylist[-1]
  def countx(self):
    return len(self.mylist)

q=stack()
q.push(10)
q.push(20)
q.push(30)
q.push(40)
q.pop()
q.peek()
q.countx()
